{% set name = "steampipe" %}
{% set version = "0.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/turbot/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 749d5ee59a8e07aae85c59fc45fd51f8549c49e2608221a3dba1ce576647bdb7
  patches:
    # Backwards compatibility with go 1.20 until go 1.21 is available in conda-forge
    - 0001-go-120.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }} 1.20
    - file
    - go-licenses >=1.0.0
    - make

test:
  commands:
    - steampipe -v
    - steampipe query --help
    - steampipe plugin list

about:
  home: https://steampipe.io
  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - LICENSE
    - license-files/
  summary: Use SQL to instantly query your cloud services.
  description: |
    Use SQL to instantly query your cloud services (AWS, Azure, GCP and more).
    Open source CLI. No DB required.
  doc_url: https://steampipe.io/docs
  dev_url: https://github.com/turbot/steampipe

extra:
  recipe-maintainers:
    - manics
