{% set name = "steampipe" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/turbot/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 59fa1f050feed5228f9e4b70098820bc0581f9e030e72a7d5798663b7ff95c0f
  patches:
    - makefile-2.3.1.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }} >=1.25
    - file
    - go-licenses >=1.0.0
    - make

test:
  commands:
    - steampipe -v
    - steampipe query --help
    # Fails to run on CI:
    # Error: plugin listing failed - Initializing database... FAILED!
    # - steampipe plugin list

about:
  home: https://steampipe.io
  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - LICENSE
    - license-files/
  summary: Use SQL to instantly query your cloud services.
  description: |
    Use SQL to instantly query your cloud services (AWS, Azure, GCP and more).
    Open source CLI. No DB required.
  doc_url: https://steampipe.io/docs
  dev_url: https://github.com/turbot/steampipe

extra:
  recipe-maintainers:
    - manics
