{% set name = "steampipe" %}
{% set version = "0.23.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/turbot/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0cd76eac829aa3a679e10e4d56260e85929d3582220b3b2530b99317c283f5d3

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }} >=1.21
    - file
    - go-licenses >=1.0.0
    - make

test:
  commands:
    - steampipe -v
    - steampipe query --help
    - steampipe plugin list

about:
  home: https://steampipe.io
  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - LICENSE
    - license-files/
  summary: Use SQL to instantly query your cloud services.
  description: |
    Use SQL to instantly query your cloud services (AWS, Azure, GCP and more).
    Open source CLI. No DB required.
  doc_url: https://steampipe.io/docs
  dev_url: https://github.com/turbot/steampipe

extra:
  recipe-maintainers:
    - manics
