{% set name = "steampipe" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/turbot/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d06db7300560fc6f17b1adebbe83d30f1876d5f0ec7bf71fa973454f0210e8fe

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }} 1.17
    - go-licenses >=0.0.44
    - make

test:
  commands:
    - steampipe -v
    - steampipe query --help
    - steampipe plugin list

about:
  home: https://steampipe.io
  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - LICENSE
    - license-files/
  summary: Use SQL to instantly query your cloud services.
  description: |
    Use SQL to instantly query your cloud services (AWS, Azure, GCP and more).
    Open source CLI. No DB required.
  doc_url: https://steampipe.io/docs
  dev_url: https://github.com/turbot/steampipe

extra:
  recipe-maintainers:
    - manics
