{% set name = "steampipe" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/turbot/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 30c7aa5b808ff409fb24588ea5703e76df6efa417fd48daf92708d32448d63ff

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go') }} 1.18
    - go-licenses >=1.0.0
    - make

test:
  commands:
    - steampipe -v
    - steampipe query --help
    - steampipe plugin list

about:
  home: https://steampipe.io
  license: AGPL-3.0-only
  license_family: AGPL
  license_file:
    - LICENSE
    - license-files/
  summary: Use SQL to instantly query your cloud services.
  description: |
    Use SQL to instantly query your cloud services (AWS, Azure, GCP and more).
    Open source CLI. No DB required.
  doc_url: https://steampipe.io/docs
  dev_url: https://github.com/turbot/steampipe

extra:
  recipe-maintainers:
    - manics
